"""
Create a new design directory structure from architecture spec.

Usage:
    python designs/framework/scripts/create_design.py --name lin_asic --tech generic180
    python designs/framework/scripts/create_design.py --name lin_asic --arch architecture.yaml
"""

import argparse
import os
import sys
import yaml
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(PROJECT_ROOT))


DEFAULT_BLOCKS = {
    "bandgap": {
        "type": "analog",
        "generator": "bandgap_ref",
        "ports": ["VDD", "VREF", "GND", "EN"],
    },
    "ldo_analog": {
        "type": "analog",
        "generator": "ldo_analog",
        "ports": ["VIN", "VOUT", "GND", "VREF", "EN"],
    },
    "ldo_digital": {
        "type": "analog",
        "generator": "ldo_digital",
        "ports": ["VIN", "VOUT", "GND", "VREF", "EN"],
    },
}

MODELS = {
    "generic180": {
        "NMOS_3P3": ".MODEL NMOS_3P3 NMOS (VTO=0.5 KP=120u LAMBDA=0.01 GAMMA=0.4 PHI=0.8)",
        "PMOS_3P3": ".MODEL PMOS_3P3 PMOS (VTO=-0.5 KP=40u LAMBDA=0.01 GAMMA=0.4 PHI=0.8)",
        "PMOS_HV": ".MODEL PMOS_HV PMOS (VTO=-0.8 KP=20u LAMBDA=0.005)",
        "NPN_VERT": ".MODEL NPN_VERT NPN (IS=1e-15 BF=100 BR=1)",
    },
}


def create_block_spec(block_name: str, block_info: dict, design_dir: Path):
    """Create spec.yaml for a block."""
    block_dir = design_dir / "blocks" / block_name
    block_dir.mkdir(parents=True, exist_ok=True)

    spec = {
        "block": {
            "name": block_name,
            "type": block_info.get("type", "analog"),
            "generator": block_info.get("generator", ""),
            "description": f"{block_name} block",
        },
        "ports": [
            {"name": p, "direction": "inout"} for p in block_info.get("ports", [])
        ],
        "specs": {},
        "testbench": {
            "dc_op": {"description": "DC operating point", "pass_criteria": "TBD"},
        },
    }

    with open(block_dir / "spec.yaml", "w") as f:
        yaml.dump(spec, f, default_flow_style=False, sort_keys=False)


def create_block_netlist(block_name: str, block_info: dict, design_dir: Path, technology: str):
    """Generate netlist for a block using BlockBuilder or create stub."""
    block_dir = design_dir / "blocks" / block_name
    block_dir.mkdir(parents=True, exist_ok=True)

    generator = block_info.get("generator", "")
    params = block_info.get("params", {})

    try:
        from simulator.agents.block_builder import BlockBuilder
        builder = BlockBuilder(technology)
        result = builder.build_block(generator, **params)
        netlist = result.get("netlist", "")
    except Exception:
        ports = " ".join(block_info.get("ports", ["VDD", "GND"]))
        netlist = f"* Stub: {block_name}\n.SUBCKT {block_name.upper()} {ports}\n.ENDS {block_name.upper()}\n"

    with open(block_dir / f"{block_name}.spice", "w") as f:
        f.write(netlist)

    return netlist


def create_testbench(block_name: str, block_info: dict, design_dir: Path, technology: str):
    """Create testbench SPICE file for a block."""
    block_dir = design_dir / "blocks" / block_name
    models = MODELS.get(technology, MODELS["generic180"])
    model_lines = "\n".join(models.values())
    ports = block_info.get("ports", ["VDD", "GND"])

    tb = f"""* Testbench: {block_name}
* Auto-generated by AMS Design Framework

.include {block_name}.spice

* Technology models
{model_lines}

* Supplies
V_VDD VDD 0 DC 3.3
V_GND_REF GND_REF 0 DC 0

* Enable
V_EN EN 0 DC 3.3

* DUT instantiation
X_DUT {' '.join(ports)} {block_name.upper()}

* Analysis
.OP

.end
"""
    with open(block_dir / "testbench.spice", "w") as f:
        f.write(tb)


def create_simulate_script(block_name: str, design_dir: Path):
    """Create per-block simulation script."""
    block_dir = design_dir / "blocks" / block_name

    script = f'''"""Simulate {block_name} block."""
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(PROJECT_ROOT))

from simulator.engine.analog_engine import AnalogEngine, DCAnalysis, TransientAnalysis

def run_dc():
    """Run DC operating point analysis."""
    engine = AnalogEngine()
    tb_path = Path(__file__).parent / "testbench.spice"
    
    # Load testbench (inline for simplicity)
    block_path = Path(__file__).parent / "{block_name}.spice"
    with open(block_path) as f:
        block_netlist = f.read()
    
    engine.load_netlist(block_netlist)
    results = engine.solve_dc()
    
    print(f"DC Operating Point - {block_name}")
    print("=" * 40)
    for k, v in sorted(results.items()):
        if "V(" in k:
            print(f"  {{k}} = {{v:.6f}} V")
    
    return results

if __name__ == "__main__":
    run_dc()
'''
    with open(block_dir / "simulate.py", "w") as f:
        f.write(script)


def create_report_template(block_name: str, design_dir: Path):
    """Create REPORT.md template."""
    block_dir = design_dir / "blocks" / block_name

    report = f"""# Block Report: {block_name}

## Status: PENDING

## DC Operating Point
| Node | Voltage | Expected | Pass |
|------|---------|----------|------|
| | | | |

## Specs Verification
| Spec | Target | Measured | Pass |
|------|--------|----------|------|
| | | | |

## Notes
- Generated by AMS Design Framework
"""
    with open(block_dir / "REPORT.md", "w") as f:
        f.write(report)


def create_design_index(design_name: str, blocks: dict, design_dir: Path):
    """Create design-level index file."""
    block_list = "\n".join(
        f"| {i+1} | {name} | {info.get('type', 'unknown')} | PENDING |"
        for i, (name, info) in enumerate(blocks.items())
    )

    index = f"""# {design_name.upper()} - Design Index

## Architecture Overview
Auto-generated design with {len(blocks)} blocks.

## Block Status

| # | Block | Type | Status |
|---|-------|------|--------|
{block_list}

## Directory Structure
```
{design_name}/
  00_INDEX.md          ← This file
  architecture.yaml    ← Architecture definition
  blocks/              ← Individual block designs
    <block_name>/
      spec.yaml        ← Block specification
      <block>.spice    ← Block netlist
      testbench.spice  ← Testbench
      simulate.py      ← Simulation script
      REPORT.md        ← Results report
  rtl/                 ← Digital RTL files
  top/                 ← Top-level integration
  VERIFICATION_STATUS.md
```

## Quick Commands
```bash
# Simulate a specific block
python designs/{design_name}/blocks/<block>/simulate.py

# Run full regression
python designs/framework/scripts/run_regression.py --design {design_name}
```
"""
    with open(design_dir / "00_INDEX.md", "w", encoding="utf-8") as f:
        f.write(index)


def main():
    parser = argparse.ArgumentParser(description="Create a new ASIC design")
    parser.add_argument("--name", required=True, help="Design name")
    parser.add_argument("--tech", default="generic180", help="Technology node")
    parser.add_argument("--arch", help="Architecture YAML file")
    parser.add_argument("--blocks", nargs="*", help="Block names to include")
    args = parser.parse_args()

    designs_dir = PROJECT_ROOT / "designs"
    design_dir = designs_dir / args.name
    design_dir.mkdir(parents=True, exist_ok=True)

    # Parse architecture or use defaults
    if args.arch and os.path.exists(args.arch):
        with open(args.arch) as f:
            arch = yaml.safe_load(f)
        blocks = {b["name"]: b for b in arch.get("blocks", [])}
        technology = arch.get("chip", {}).get("technology", args.tech)
    else:
        technology = args.tech
        if args.blocks:
            blocks = {name: DEFAULT_BLOCKS.get(name, {"type": "analog", "ports": ["VDD", "GND"]})
                      for name in args.blocks}
        else:
            blocks = DEFAULT_BLOCKS

    print(f"Creating design '{args.name}' with {len(blocks)} blocks...")
    print(f"Technology: {technology}")

    # Create directories
    (design_dir / "blocks").mkdir(exist_ok=True)
    (design_dir / "rtl").mkdir(exist_ok=True)
    (design_dir / "top").mkdir(exist_ok=True)

    # Generate each block
    for block_name, block_info in blocks.items():
        print(f"  Generating block: {block_name}")
        create_block_spec(block_name, block_info, design_dir)
        create_block_netlist(block_name, block_info, design_dir, technology)
        create_testbench(block_name, block_info, design_dir, technology)
        create_simulate_script(block_name, design_dir)
        create_report_template(block_name, design_dir)

    # Create design index
    create_design_index(args.name, blocks, design_dir)

    # Create architecture.yaml
    arch_data = {
        "chip": {"name": args.name.upper(), "technology": technology},
        "blocks": [{"name": n, **info} for n, info in blocks.items()],
    }
    with open(design_dir / "architecture.yaml", "w") as f:
        yaml.dump(arch_data, f, default_flow_style=False, sort_keys=False)

    print(f"\nDesign created at: {design_dir}")
    print(f"See {design_dir / '00_INDEX.md'} for navigation.")


if __name__ == "__main__":
    main()
