"""
AMS Simulator Database Layer.

Provides structured SQLite storage for technologies, device models,
circuit designs, simulation configs, results, waveform data,
projects, design specs, and campaign management.
"""

from simulator.db.connection import SimDB
from simulator.db.models import (
    Technology,
    ProcessCorner,
    DeviceModel,
    LibraryComponent,
    CircuitDesign,
    SimulationConfig,
    SimulationResult,
    StandardCell,
    SweepRun,
    ProjectRecord,
    DesignSpecRecord,
    CampaignRecord,
    CampaignResultRecord,
)
from simulator.db.queries import (
    save_technology,
    get_technology,
    list_technologies,
    save_device_model,
    get_device_models,
    get_model_spice_text,
    get_all_models_spice,
    save_circuit,
    get_circuit,
    get_circuit_by_id,
    get_circuit_history,
    save_simulation_config,
    save_result,
    get_results_for_circuit,
    save_library_component,
    get_library_component,
    list_library_components,
    save_project,
    get_project,
    list_projects,
    save_design_spec,
    get_design_specs,
    save_campaign,
    update_campaign_status,
    get_campaign_by_id,
    get_campaigns,
    save_campaign_result,
    get_campaign_results,
    get_campaign_summary,
)

__all__ = [
    "SimDB",
    "Technology",
    "ProcessCorner",
    "DeviceModel",
    "LibraryComponent",
    "CircuitDesign",
    "SimulationConfig",
    "SimulationResult",
    "StandardCell",
    "SweepRun",
    "ProjectRecord",
    "DesignSpecRecord",
    "CampaignRecord",
    "CampaignResultRecord",
    "save_technology",
    "get_technology",
    "list_technologies",
    "save_device_model",
    "get_device_models",
    "get_model_spice_text",
    "get_all_models_spice",
    "save_circuit",
    "get_circuit",
    "get_circuit_by_id",
    "get_circuit_history",
    "save_simulation_config",
    "save_result",
    "get_results_for_circuit",
    "save_library_component",
    "get_library_component",
    "list_library_components",
    "save_project",
    "get_project",
    "list_projects",
    "save_design_spec",
    "get_design_specs",
    "save_campaign",
    "update_campaign_status",
    "get_campaign_by_id",
    "get_campaigns",
    "save_campaign_result",
    "get_campaign_results",
    "get_campaign_summary",
]
